### ISSUE TITLE
Integrate it with npm and bower

### ISSUE THREAD

**Issue by ankitjain28may** [aka-jain/MessageUp.js#6]

**Comment by aka-jain** [comment]
@ankitjain28may are you integrating it?

**Comment by ankitjain28may** [comment]
I can do so..!

**Comment by aka-jain** [comment]
Go ahead!

**Comment by ankitjain28may** [comment]
this package is published through my account n i want that this package must be published from your account.

**Comment by aka-jain** [comment]
Sorry I'm not getting it, which package you are talking about?

**Comment by ankitjain28may** [comment]
when i integrate this repo, i used my npmjs account to integrate with npm, so i want that this project must be published through your account

**Comment by aka-jain** [comment]
Oh Okay, got it. Will do it.

**Comment by ankitjain28may** [comment]
ok sir, so if you can give me or account credentials thn i will integrte else i will share the ownership?

**Comment by aka-jain** [comment]
Ok, let me think whether integrating it with npm will be useful or not. I get back to you soon.

**Comment by ankitjain28may** [comment]
ok sir

**Comment by aka-jain** [comment]
@ankitjain28may I have added a basic npm dependency but I don't think that we need it for now. And bower dependency is already there. Just check and let me know if you want some more changes. Thanks.

**Comment by ankitjain28may** [comment]
ok sir, i wil check
