### ISSUE TITLE
Add a DEMO

### ISSUE THREAD

**Issue by itaditya** [aka-jain/MessageUp.js#8]
Plugins definitely require a demo page , with code snippets highlighting their effects. I would like to make a demo page for this .

**Comment by aka-jain** [comment]
@itaditya I already made one, please check index.html. If you want to change or improve that then go ahead please :)

**Comment by itaditya** [comment]
Yeah , but where is the online link ?

**Comment by aka-jain** [comment]
Want to host it on gh-pages?

**Comment by itaditya** [comment]
Yeah Sure

**Comment by aka-jain** [comment]
Sure, assigning this to you. Go ahead.

**Comment by itaditya** [comment]
Just want to know one thing , as you are already using gh-pages branch for the documentation , how can I use something like this http://aka-jain.github.io/MessageUp.js/demo/ to show a DEMO .

**Comment by aka-jain** [comment]
Hmmm... I was thinking that too, let's host it on Heroku. Thoughts?

**Comment by itaditya** [comment]
Or we can use surge for hosting as it it is for static websites

**Comment by aka-jain** [comment]
Amm... Na let's go with Heroku. Will you please make a Server file for the configuration?
